### PR TITLE
 Italian translations fix 

### PR DESCRIPTION
**Pull request by bacca87**
I've fixed the italian translation and resized a little bit the "remind me later" button in order to contain bigger strings like the italian one "ricordamelo più tardi".

bacca87/great2#69

### CODE REVIEW

**Comment by ravibpatel** [comment]
I made some changes can you test it from your end. If everything works tell me if you want a new release.

**Comment by bacca87** [comment]
Ok i've tested it and it's ok!

**Comment by ravibpatel** [comment]
Do you want a new NuGet release?

**Comment by bacca87** [comment]
Up to you... for sure would be better a new release!

**Comment by ravibpatel** [comment]
I updated the NuGet package to v1.5.6. It should be available soon.

**Pull request merged**
