### PR TITLE
7zip support, http basic auth, archive password

### PR DESCRIPTION
**Pull request by schland**
added 7zip support in ZipExtract using embedded SharpCompress library, should be now easy to add Rar and other archives types too.

Added support for HttpBasicAuth (getting Update XML and Update Archive)

Added support for Archive Password (currently only 7zip), but should be easy to add for other types

Please ignore Build Configuration changes, i made.

### CODE REVIEW

**Comment by zgabi** [comment]
I have a concurrent PR about the basic authentication (#200), where I need authentication only for the download file. So please allow to specify different username/password pairs for the xml and the installer file.

**Comment by ravibpatel** [comment]
@schland Thanks for the pull request. Your pull request increases the .NET framework version requirement so I will add it in version 2.0.

**Comment by etisdew** [comment]
Is there still a version two in the works? I'm interested to see what you have planned as I consider adapting your solution to my problem. More broadly, will you be taking any of the other current PRs with you into v2? I'm currently reviewing them to see if they also might offer value to my problem of distributing updates. I'm very impressed with how you handle issue reports, and it seems like a very well appreciated package in the community.

**Comment by ravibpatel** [comment]
@etisdew  First, I am gonna implement all functionality of the current version into the standard version if that's possible. Also, my plan is to do 2 separate libraries 1 for Winforms and 1 for WPF using .NET Standard library when it finishes. I didn't find time to work on v2 recently so it might take some time before I finish it. You can check out the v2 branch to see the work in progress.

**Pull request closed without merging**
