### PR TITLE
Add a BeforeInstallingEvent event

### PR DESCRIPTION
**Pull request by aamereller**
The BeforeInstallingEvent event has been added in order to meet the current requirements of Technica Engineering GmbH for this software.

### CODE REVIEW

**Comment by ravibpatel** [comment]
ApplicationExitEvent fires before installation begin, so can you tell me why BeforeInstallingEvent is needed? Also, this can also be done by handling the update manually, that way you can do whatever you want before download begins as shown in [the example](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually).

**Comment by kayoub5** [comment]
@ravibpatel we have a rather big installer (more than half a gigabyte), download could take long, so user resume using the application while download is in progress.

We need a hook to warn user that application is about to exit and installation will start after the download is complete.

the start of the download does not necessarily mean the start of the installation (download could be fail due to network issues)

applications that want to perform some changes/logic based on the downloaded file content have no means to do so.

**Comment by ravibpatel** [comment]
@kayoub5 You can still handle update logic and squeeze your code before calling DownloadUpdate method.

**Comment by kayoub5** [comment]
> @kayoub5 You can still handle update logic and squeeze your code before calling DownloadUpdate method.

Currently there is no API to put logic between the download end and before the installation actually starts.

**Comment by ravibpatel** [comment]
ApplicationExitEvent is called after the download ends and before the installation actually starts, so you can put logic there.

**Pull request closed without merging**
