### PR TITLE
Initial commit of WebView2 enabled AutoUpdater.NET

### PR DESCRIPTION
**Pull request by tip2tail**
Proposed solution for #527 

For review @ravibpatel

### CODE REVIEW

**Comment by tip2tail** [comment]
Sorry for the massive change on the project file, that was not shown in VS Code when committing!  Baring one section at the bottom for the new WebView2 package, it is line ends/whitespace.

**Comment by tip2tail** [comment]
Thank you for the changes @ravibpatel 

Am I to assume you intend to simply replace the WebBrowser control with WebView 2 rather than make this optional?
Do you have a timescale on when you plan to release a new build with this functionality?  I ask, as my project which uses this is about to have a major release and I would love to include this with it.

**Comment by ravibpatel** [comment]
Thanks for the PR. If WebView 2 is available, then, it should be used instead of older web browser control. There is no point in making it optional if there is WebView 2 runtime available on the system. I will merge it and do some testing and then I will release it.

**Comment by ravibpatel** [comment]
Can you check the latest NuGet package from [here](https://ci.appveyor.com/api/buildjobs/5tcx89plcrx32cju/artifacts/Autoupdater.NET.Official.1.7.1.nupkg)? Let me know how it goes. If it works fine, then I will push the release to NuGet. You will be able to test it out by adding it in Offline NuGet Package Source in Visual Studio.

**Comment by ravibpatel** [comment]
I pushed the updated package to NuGet.

**Pull request merged**
