### PR TITLE
Added option to set owner in WPF and Windows Forms

### PR DESCRIPTION
**Pull request by Fruchtzwerg94**
Added option to set owner in WPF and Windows Forms to prevent hidden popups if owner is top most.

### CODE REVIEW

**Comment by ravibpatel** [comment]
I tested this out and find out that I can set the TopMost to true for all the forms, and it has the same effect. Update windows should be always on top anyway, so I think it will be much better because user don't have to set the owner manually. What do you think about this?

**Comment by Fruchtzwerg94** [comment]
I personally do not like to set all Forms to TopMost by default. Here are some reasons why I think like this:

- Setting the dialogs to TopMost by default could disturb some users which are working in other windows, postponing the update decision to later
- Setting the dialogs to TopMost by default could suddenly pop up (also if another application is in front) which could lead to wrong inputs if the user does not recognize it
- MessageBoxes are not handled as TopMost anyway with this approach
- Setting the Owner (which is still optionally) clearly assigns the popups to a corresponding application window

**Comment by ravibpatel** [comment]
Your points are valid. I added some changes to it to prevent an issue shown [here](https://stackoverflow.com/a/20661147/1273550).

**Comment by Fruchtzwerg94** [comment]
Good catch, that was definitively not in my mind. Good to test in different environments / projects.

**Pull request merged**
