### PR TITLE
Enable custom update form and download update dialog.

### PR DESCRIPTION
**Pull request by noctis0430**
1. Custom update form and download update dialog must implements `AutoUpdaterDotNET.IForm`.
2. Set `AutoUpdater.UpdateFormType` and/or `AutoUpdater.DownloadUpdateDialogType` to use custom update form/download update dialog.

### CODE REVIEW

**Comment by ravibpatel** [comment]
Thanks for the pull request. I will review it asap.

**Comment by ravibpatel** [comment]
I tested the pull request but sorry, I can't merge it cause What you did here can already be done by handling the update manually using the event as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually). I'm gonna keep it open just in case if anyone wants this type of solution.

**Comment by noctis0430** [comment]
@ravibpatel hmm you're right. Maybe this approach can be used for custom download dialog instead?

**Comment by ravibpatel** [comment]
Both can be achievable via the same event cause you have all the data you need (Args object) passed into the event. Instead of calling the AutoUpdater.DownloadUpdate method, users can provide their own dialog there.

**Comment by noctis0430** [comment]
Yeah that's the case when the update is not mandatory. But if the update is mandatory, default download update dialog will be used, no?

**Comment by ravibpatel** [comment]
No, even for mandatory updates event will be called and users can access Mandatory and UpdateMode values from args object. Standard dialogs aren't forced when you use the event. You can handle it however you want.

**Comment by noctis0430** [comment]
Ahh I see what you mean already. OK I will use your approach for custom update form and custom download dialog form.

**Comment by dardanshabani** [comment]
> Both can be achievable via the same event cause you have all the data you need (Args object) passed into the event. Instead of calling the AutoUpdater.DownloadUpdate method, users can provide their own dialog there.

How this can be done: " Instead of calling the AutoUpdater.DownloadUpdate method, users can provide their own dialog there", how to start downloading and not showing download dialog of autoUpdater? Is any other method that I can start downloading, cause as I saw, download starts in this method?

**Pull request closed without merging**
