### PR TITLE
.NET Core WPF and .NET Core WPF Test 

### PR DESCRIPTION
**Pull request by cdesch**
Here is my first attempt at setting up a new .Net Core WPF Class Library Project and a .Net Core WPF test application. (related to issue #254) 

Please give it a try and see if it works as you want it to. 

Here are some details.

AutoUpdater.NET.Core.WPF - this projects implements the AutoUpdater.NETStandard just as the AutoUpdater.NET.WPF project did

 - Added Microsoft.Windows.Compatibility as a Nuget dependency
 - Added Microsoft.Toolkit.Wpf.UI.Controls.WebView as a Nuget dependency
 
AutoUpdaterTest.NET.Core.WPF - This is the test project similar to AutoUpdaterTestWPF that will use the  AutoUpdater.NET.Core.WPF to update.

### CODE REVIEW

**Comment by cdesch** [comment]
@ravibpatel I'm not sure how to resolve this conflict. Is this something you can do?

**Comment by ravibpatel** [comment]
@cdesch You must open the pull request in the v2.0 branch. You opened it in master branch. That's why it raised the conflict.

**Comment by ravibpatel** [comment]
@cdesch Also, I think name should be AutoUpdater.NET.Core.WPF to AutoUpdater.NETCore.WPF. Sounds cooler. Let me know what you think.

**Comment by cdesch** [comment]
@ravibpatel I can rename it. Let me close this pull request and fix the name and make a pull request to the 2.0 branch

**Comment by cdesch** [comment]
@ravibpatel do you want the AutoUpdaterTest.NET.Core.WPF to be named  AutoUpdaterTest.NETCore.WPF too?

**Comment by ravibpatel** [comment]
@cdesch Yeah, it will sound better.

**Pull request closed without merging**
