### PR TITLE
Bug fix for running .msi installers

### PR DESCRIPTION
**Pull request by ghost1face**
Related to issue: #137  This resolves and uses case insensitive comparison for file extensions

### CODE REVIEW

**Comment by ravibpatel** [comment]
@ghost1face Thanks for the pull request.

**Comment by ghost1face** [comment]
Thanks for merging, any update on when the latest NuGet package will be deployed?

**Comment by ravibpatel** [comment]
@ghost1face I will deploy it this weekend or next week.

**Comment by ravibpatel** [comment]
@ghost1face New version is available with this fix.

**Comment by ghost1face** [comment]
Great, thanks!

**Pull request merged**
