### PR TITLE
No new version dialog, plus some new settings.

### PR DESCRIPTION
**Pull request by CitizenMrL**
This is a great project, which saved me a lot of time, so I thought I could contribute a little.

I made some minor changes, based on my use case.

1. Added NoNewVersionDialog form, with corresponding ShowNoNewVersion setting. This is for manual checks made by the user, to let him know that version checking went fine, but there is nothing to download.

2. Added IgnoreRemindMeLater setting. This is for situation when user chose 'remind me' with some long stretch of time and now has to wait, although he changed his mind.

3. Added ResetSkipVersion setting. This is for situation when user chose to skip version, but changed his mind. New version may arrive in a very long time or even never, so user would be stuck with old version.

4. Changed AppTitle to public. Sometimes assembly name is different from program name and may look ulgy for the user (example: assembly name is CitizenMrL.SolutionName.Clients.Wpf.BigClient, but app name in fact is SolutionName).

All new settings have defaults that make them inactive, they must be explicitly set by the developer using AutoUpdater.

Caveat: I didn't know how to translate NoNewVersionDialog to all the languages, so there are only english and polish versions.

### CODE REVIEW

**Comment by ravibpatel** [comment]
Although options added by you are nice additions, If I add IgnoreRemindLater and ResetSkipVersion then there is no purpose left for both those buttons. I will add an option to hide RemindLater button soon so the developer can control both button visibility.

I like your suggestion about changing AppTitle to public. I like to implement it but your pull request contains lots of changes.

Also if I add NoNewVersionDialog developers who like to check for update at the start of the application will be shown that dialog every time they open the application if there is no new update. Most developers will like to add it to the startup of the application because that's when user are not doing anything meaningful and AutoUpdater can safely close the application.

**Comment by CitizenMrL** [comment]
> If I add IgnoreRemindLater and ResetSkipVersion then there is no purpose left for both those buttons.
[...]
> Also if I add NoNewVersionDialog developers who like to check for update at the start of the application will be shown that dialog every time they open the application if there is no new update. Most developers will like to add it to the startup of the application because that's when user are not doing anything meaningful and AutoUpdater can safely close the application.

No no, there is a purpose for those buttons and the dialog won't be shown always. Let me explain in context of my own usage of Autoupdater.

My changes are set to false by default, so they are not active when Autoupdater is used in a standard way.
So when I do 
`Autoupdater.Start(...)`
at the start of application, RemindMeLater is not ingored, SkipVersion is not reset and no dialog is shown when there is no new version.
But I also have a button in my app "Check for updates", when user clicks that button I want the version to be checked and I want user to be informed when no new version is found.
So in the click event I do
`Autoupdater.IgnoreRemindmeLater = true;
 Autoupdater.ResetSkipVersion = true;
 Autoupdater.ShowNoNewVersinoDialog = true;
 Autoupdater.Start(...)`

So, everything works as it was, unless user explicitly clicks 'Check for updates'.

**Comment by ravibpatel** [comment]
Sorry, But still I think if there are options to hide both Remind Later and Skip buttons then there is no need for IgnoreRemindmeLater and ResetSkipVersion options on the developer side.

Also, you changed projects .NET version to 4.6 which I want to keep it to 2.0. Sorry, but I can't merge this request.

**Comment by CitizenMrL** [comment]
I think you don't understand what my changes are intended to do.
The use case is simple: if user **already clicked Skip or Remind Later**, he has **no way of checking for updates**. Those decisions are stored in registry, which user knows nothing about.

**User**: I cliked Remind Later in 10 days by mistake, how do I check for updates in this situation?
**Autoupdater**: You don't. Wait 10 days.

**User**: I clicked Skip Version by mistake and that's the last version the app will ever have. What do I do?
**Autoupdater**: Nothing. No new version for you ever.

As for the .Net 4.6, I don't have 2.0 SDK installed, so VS couldn't open the project and changed the version for me. My changes are compatible with 2.0, so the project can be kept 2.0 without problems.

**Comment by ravibpatel** [comment]
I completely understand what you are trying to tell me but instead of adding an option for it I am thinking of adding an extra field mandatory that if developer set it to true skip and remind later options are ignored. This will make things in control of the developer. What do you think about it? Also why you created the new dialog for NoNewVersion. I think message box would be enough?

**Comment by CitizenMrL** [comment]
> I completely understand what you are trying to tell me but instead of adding an option for it I am thinking of adding an extra field mandatory that if developer set it to true skip and remind later options are ignored. This will make things in control of the developer. What do you think about it?

That would be great! It's exactly what I tried to achieve with my changes.

> Also why you created the new dialog for NoNewVersion. I think message box would be enough?

Yeah, message box would be enough. At first I wanted that window to have more information, but I changed my mind and it stayed that way. Message box is definitely the way to go.

**Pull request closed without merging**
