### PR TITLE
Allow more complex WebRequest authentications when downloading data e.g. from Azure Storage

### PR DESCRIPTION
**Pull request by jay1891**
Hi Ravi,

These adjustments allow to have more advanced authentications (web request headers) when downloading files. Like I mentioned in a previous comment, these complexe authentication scenarios are requirements from Azure Storage.

I tested it with our application, and it should all work. This is also not a breaking change, in its normal use of AutoUpdater.

Is this change ok for you, and could this be merged?

### CODE REVIEW

**Comment by jay1891** [comment]
Hi Ravi,

If this PR is ok for you, could a new nuget release be created or what is possible?

**Comment by ravibpatel** [comment]
Hi, 

It looks fine but I think there is one thing we can do to improve it. Instead of Adjust, we can name the method Apply and then we can move the code responsible for applying Authorization header via ToString call into Apply method. That way there will be only 1 step needed to apply the Authorization header. Right now, we are adding Authorization header and then calling Adjust method which is not always necessary for every authentication. So by doing this we can remove the ToString override and make Apply useful in every Authentication scenario.

Let me know what you think about it.

**Comment by jay1891** [comment]
Hi Ravi,

Yes, that would make it cleaner. I make the adjustment today and create a PR.

**Comment by jay1891** [comment]
Hi Ravi,

I updated the pull request. I also added the class AzureStorageAuthentication to the project AutoUpdaterTestWPF. I don't know if you would find it useful to actually embed it in AutoUpdater but at least it is maybe interesting to add it to the documentation as an example? If you don't want it, then please just delete it. It is the current implementation I use.

What is your idea, and could it be merged and released?

**Comment by ravibpatel** [comment]
Did you test it fully from your side? If it is working fine then let me know I'll merge it.

**Comment by jay1891** [comment]
Hi Ravi,

To be sure, I shall work with my local release in my application for a few days. If I see there any issues or if all is ok, I shall let it know.

**Comment by jay1891** [comment]
Hi Ravi,

Could I ask you the following?

**1)**
My application has a high dpi scaling. For winforms this is problematic as you can see in the pictures below.

Because AutoUpdater has only some simple small text, is it ok that I adjust the 2 problematic text layouts a little so in the english language there will be no high dpi scaling issue? Specificly I would start the text earlier on another line, so it can't drop of. And in case of the download amout, I would align it to the left and under the progress bar. Is this ok to add? It would be very helpful to solve the dpi scaling issue in a simple way.

2019-09-27 19_32_44-AutoUpdaterTestWPF 2 1 19270 12 is available!

2019-09-27 19_32_54-Software Update

**2)**
My application uses a lot of resources, and when the application is going to update, AutoUpdater tries to stop the application. I use the ApplicationExitEvent for that. But the installer is then already running parallel with exiting the application, and the installer shows a popup that it wants to close the application by force, because at that point the exiting of the application is not going fast enough. I want to prevent that the user sees this popup. For that I added an event which is invoked before the installer process is executing namely "UpdateInstallingEvent". The application has then here the possibility to synchronously already start disposing resources. When enough resources are disposed, it then runs the update process (exe), and the ApplicationExitEvent is invoked. I already implemented this, event "UpdateInstallingEvent". Is it ok I keep this in the PR?

Both of the solutions are small solutions which helps a lot, and none is a breaking change. 

Kind regards,

**Comment by jay1891** [comment]
Hi Ravi, 

Related to the high dpi problem I have the following solutions (see pictures below)
I tested it, and it looks ok on a default dpi or a high scale dpi.

What is your idea about this?

2019-09-27 21_53_41-Software Update

2019-09-27 22_19_18-AutoUpdaterTest 2 0 0 0 is available!

**Comment by ravibpatel** [comment]
I appreciate if you do separate PR for each functionality. It will be easier to track the change. 

I like the UI idea of Download dialog but I'm not sure about the UpdateDialog. It looks better with 1 line rather than 3 lines. I don't like to overwhelm devs with more event. The effectiveness of UpdateInstallingEvent will be totally dependant on Dev's implementation so I'm not sure about it.

**Comment by jay1891** [comment]
Hi Ravi,

I don't know git enough to do this, and reverting things is not working. I will close the pull request and leave it like that. Thank you for your information and evaluating this.

**Comment by jay1891** [comment]
Hi Ravi,

Related to "The effectiveness of UpdateInstallingEvent will be totally dependant on Dev's implementation so I'm not sure about it". 

I don't understand what you mean here. The event is just a possibility to do something before the actual update (exe) will run. It has no specific requirement what needs to be done, like e.g. the CheckForUpdateEvent. So there is no effectiveness measurement related to a requirement by definition, in contrary to "ApplicationExitEvent" and "CheckForUpdateEvent", both have a specific requirement "Exit application" and "check for update/do update". So there a clear effectiveness can be measured, but not with the UpdateInstallingEvent.

At the end the effectiveness of any implementation is dependent on that implementation and its requirement. This is a general principle of any implementation. But for the UpdateInstallingEvent there is no real requirement, but for the other events there is. For example:

- if someone is creating an event handler for ApplicationExitEvent and doesn't exit the application. How effective is that implementation (dev)?

- if someone is creating an event handler for CheckForUpdateEvent and doesn't check for the update. How effective is that implementation (dev)?

I hope you see my point.

Kind regards,

**Comment by ravibpatel** [comment]
Hi Jay,

I didn't mean to disregard your idea of the event but it will hard to tell devs what kind of thing they should do in UpdateInstallingEvent to make Application exit properly that's what I meant by effectiveness. Also, if you check out the call to ApplicationExitEvent you will see that it will be called few milliseconds after the call to the UpdateInstallingEvent so will it make any difference? I didn't try logging using the timer but it shouldn't take long cause there are only few lines of code between them.
 
Flow is run update executable, exit Download Dialog, Update Dialog and run ApplicationExitEvent so I think that should only take few milliseconds.

I tried the UI changes too and I like the Download dialog idea but it needs adjusting for normal DPI screen. 

[https://prnt.sc/pc3fxd](https://prnt.sc/pc3fxd)

I know you worked hard on these changes and I appreciate the effort.

**Comment by jay1891** [comment]
Hi Ravi,

Related to: _"if you check out the call to ApplicationExitEvent you will see that it will be called few milliseconds after the call to the UpdateInstallingEvent so will it make any difference?"_ 
And to: _"Flow is run update executable, exit Download Dialog, Update Dialog and run ApplicationExitEvent so I think that should only take few milliseconds."_

The functionality of the AutoUpdater takes only a few milliseconds without any custom logic implemented, and there is no issue when it is just a sample or very basic application. But the application I'm working uses 9 monitors, all with its own main window and ui thread. In the background resources are being used, and which interact with cloud services. When the application exits gracefully, it needs to shutdown all 9 main windows, call cloud services to communicate a graceful ending (if possible), and dispose local resources. This all takes at least 5 seconds and in the mean time the installer is already started and wants to shutdown the application by force or is blocked.

Sorry for the update dialog. I can not reproduce it locally at a normal dpi, but I tried to fix it. 

If I could I would help with git, but sadly I'm not experienced enough at the moment to do a revert/reset/... I'm trying now for a few hours and I see actually almost nothing happening in the PR. So I don't understand it. Locally I get it changed, but getting it in the remote branch is not working. I think now I lost all connection with this PR. I tried it also with the SmartGit client, but it is also not helping. Sorry for my current inexperience with this. I would say just leave it as it is.

Kind regards,

**Pull request closed without merging**
